version: '3.5'

services:
  postgres:
    image: "postgres:12.0"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  api:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/jaguaribefood
      - app-gems:/app-gems
    stdin_open: true
    tty: true

volumes:
  redis:
  postgres:
  app-gems:
  elastic:
