default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: one_bit_food_development

test:
  <<: *default
  database: one_bit_food_test

production:
  <<: *default
  database: one_bit_food_production